### ISSUE TITLE
Batch processing vignette text doesn't match luq_units / luq_units_merged column order

### ISSUE THREAD

**Issue by stevenchong** [NCEAS/metajam#68]
In the batch processing vignette, "**Perform checks on the units**" section, one of the comments and the Conclusion section state that the last two sampling sites are `RioIcacos` and `RioMameyesPuenteRoto`.  However, I'm seeing that `RioMameyesPuenteRoto` and `RioIcacos` appear as the first and last sampling sites in the `luq_units` and `luq_units_merged` dataframes, respectively.  I think you need to sort the dataframe columns alphabetically to match what is stated in the vignette.  Alternatively, you could remove the words "2 last" from the comment and Conclusion section in the vignette.

**Comment by brunj7** [comment]
Thanks for the careful review @stevenchong! The problem comes from the fact that I changed the way we are listing the datasets. `doenload_d1_files` returns the datasets in the same order than listing in the csv, where as listing the directory content is alphabetical on the filename.

For both methods to match, I added an `dplyr::arrange` on the filename when reading the csv listing the files to be downloaded.
